// lchannels - session programming in Scala
// Copyright (c) 2017, Alceste Scalas and Imperial College London
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// * Redistributions of source code must retain the above copyright notice,
//   this list of conditions and the following disclaimer.
//
// * Redistributions in binary form must reproduce the above copyright notice,
//   this list of conditions and the following disclaimer in the documentation
//   and/or other materials provided with the distribution.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.

/** Multiparty protocol classes for role Carol in three-buyer example.
 *  The classes in this package have been automatically generated from the
 *  multiparty game protocol:
 *  https://github.com/alcestes/scribble-java/blob/linear-channels/modules/linmp-scala/src/test/scrib/ThreeBuyer.scr
 *  
 * @author Alceste Scalas <alceste.scalas@imperial.ac.uk> */
package lchannels.examples.threebuyer.protocol.carol

import scala.concurrent.duration.Duration
import lchannels._
import lchannels.examples.threebuyer.protocol.binary
import lchannels.examples.threebuyer.protocol.bob.MPOkAOrQuitA
import java.time.ZonedDateTime

// Local type for role Carol:
//    bob&{Contrib(Int).bob&{Delegate(alice⊕{OkA(Unit).seller⊕{OkS(Unit).seller⊕{Address(String).seller&{Deliver(ZonedDateTime).end}}}, QuitA(Unit).seller⊕{QuitS(Unit).end}}).bob⊕{OkC(Unit).end, QuitC(Unit).end}}}

// Input message types for multiparty sessions (autogenerated by Scribble)
case class Contrib(p: Int, cont: MPDelegate)
case class Delegate(p: MPOkAOrQuitA, cont: MPOkCOrQuitC)
case class Deliver(p: ZonedDateTime)

// Output message types for multiparty sessions (autogenerated by Scribble)
case class OkC(p: Unit)
case class QuitC(p: Unit)
case class OkA(p: Unit)
case class QuitA(p: Unit)
case class OkS(p: Unit)
case class Address(p: String)
case class QuitS(p: Unit)

// Multiparty session classes (autogenerated by Scribble)
case class MPContrib(bob: In[binary.Contrib]) {
  def receive(implicit timeout: Duration = Duration.Inf) = {
    bob.receive(timeout) match {
      case m @ binary.Contrib(p) => {
        Contrib(p, MPDelegate(m.cont))
      }
    }
  }
}

case class MPDelegate(bob: In[binary.Delegate]) {
  def receive(implicit timeout: Duration = Duration.Inf) = {
    bob.receive(timeout) match {
      case m @ binary.Delegate(p) => {
        Delegate(p, MPOkCOrQuitC(m.cont))
      }
    }
  }
}

case class MPOkS(alice: Unit, seller: Out[binary.OkSOrQuitS]) {
  def send(v: OkS) = {
    val cnt = seller !! binary.OkS(v.p)_
    MPAddress(alice, cnt)
  }
}

case class MPAddress(alice: Unit, seller: Out[binary.Address]) {
  def send(v: Address) = {
    val cnt = seller !! binary.Address(v.p)_
    MPDeliver(alice, cnt)
  }
}

case class MPDeliver(alice: Unit, seller: In[binary.Deliver]) {
  def receive(implicit timeout: Duration = Duration.Inf) = {
    seller.receive(timeout) match {
      case m @ binary.Deliver(p) => {
        Deliver(p)
      }
    }
  }
}

case class MPQuitS(alice: Unit, seller: Out[binary.OkSOrQuitS]) {
  def send(v: QuitS) = {
    val cnt = seller ! binary.QuitS(v.p)
    ()
  }
}

case class MPOkCOrQuitC(bob: Out[binary.OkCOrQuitC]) {
  def send(v: OkC) = {
    val cnt = bob ! binary.OkC(v.p)
    ()
  }
  def send(v: QuitC) = {
    val cnt = bob ! binary.QuitC(v.p)
    ()
  }
}
